"""Alter check tbl add type col

Revision ID: 3928851b22ec
Revises: e9bffff46348
Create Date: 2025-08-30 16:04:50.309104

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3928851b22ec"
down_revision: Union[str, None] = "e9bffff46348"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    sa.Enum("HUMAN", "AI", name="checktype").create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("checks", sa.Column("type", sa.Enum("HUMAN", "AI", name="checktype"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("checks", "type")
    # ### end Alembic commands ###
    sa.Enum("HUMAN", "AI", name="checktype").drop(op.get_bind(), checkfirst=True)
