"""Create user profile tbl

Revision ID: 736af655812f
Revises:
Create Date: 2025-06-21 21:45:09.857062

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "736af655812f"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_profiles",
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    # ### end Alembic commands ###

    op.execute(
        """
        CREATE OR REPLACE FUNCTION public.sync_auth_user()
        RETURNS TRIGGER AS $$
        BEGIN
        IF TG_OP = 'INSERT' THEN
            -- only insert the id, ignore if already exists
            INSERT INTO public.user_profiles (id, email)
            VALUES (NEW.id, NEW.email)
            ON CONFLICT DO NOTHING;
            RETURN NEW;
        ELSIF TG_OP = 'DELETE' THEN
            -- cascade delete on mirror
            DELETE FROM public.user_profiles
            WHERE id = OLD.id;
            RETURN OLD;
        END IF;
        END;
        $$ LANGUAGE plpgsql;    
        
        CREATE TRIGGER sync_auth_user_insert
        AFTER INSERT ON auth.users
        FOR EACH ROW
        EXECUTE FUNCTION public.sync_auth_user();
        
        CREATE TRIGGER sync_auth_user_delete
        AFTER DELETE ON auth.users
        FOR EACH ROW
        EXECUTE FUNCTION public.sync_auth_user();
        
        GRANT USAGE ON SCHEMA public TO supabase_auth_admin;
        GRANT SELECT, INSERT, DELETE ON public.user_profiles TO supabase_auth_admin;
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute(
        """
        REVOKE USAGE ON SCHEMA public FROM supabase_auth_admin;
        REVOKE INSERT, DELETE ON public.user_profiles FROM supabase_auth_admin;
        
        DROP TRIGGER IF EXISTS sync_auth_user_insert ON auth.users;
        DROP TRIGGER IF EXISTS sync_auth_user_delete ON auth.users;
        DROP FUNCTION IF EXISTS public.sync_auth_user();
        """
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_profiles")
    # ### end Alembic commands ###
