"""Cascade feature deletion

Revision ID: 487dfbd44219
Revises: accbc0c4562a
Create Date: 2025-08-30 09:32:25.241329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '487dfbd44219'
down_revision: Union[str, None] = 'accbc0c4562a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('checks_feature_id_fkey', 'checks', type_='foreignkey')
    op.create_foreign_key('checks_feature_id_fkey', 'checks', 'features', ['feature_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('eval_results_check_id_fkey', 'eval_results', type_='foreignkey')
    op.create_foreign_key('eval_results_check_id_fkey', 'eval_results', 'checks', ['check_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('eval_results_check_id_fkey', 'eval_results', type_='foreignkey')
    op.create_foreign_key('eval_results_check_id_fkey', 'eval_results', 'checks', ['check_id'], ['id'])
    op.drop_constraint('checks_feature_id_fkey', 'checks', type_='foreignkey')
    op.create_foreign_key('checks_feature_id_fkey', 'checks', 'features', ['feature_id'], ['id'])
    # ### end Alembic commands ###
