"""Create ROU table

Revision ID: 898abe5f7816
Revises: 089d5b4084da
Create Date: 2025-08-27 09:37:02.325475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '898abe5f7816'
down_revision: Union[str, None] = '089d5b4084da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regulatory_obligation_units',
    sa.Column('type', sa.Enum('HUMAN', 'AI', name='routype'), nullable=False),
    sa.Column('canonical_text', sa.Text(), nullable=False),
    sa.Column('desc', sa.Text(), nullable=False),
    sa.Column('obligations', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('jurisdiction', sa.String(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('regulatory_obligation_units')
    # ### end Alembic commands ###
