"""add terminology table

Revision ID: 83c8bc13eed2
Revises: 0631bf67b7b8
Create Date: 2025-08-30 15:52:39.060712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83c8bc13eed2'
down_revision: Union[str, None] = '0631bf67b7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('terminologies',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_terminologies_key'), 'terminologies', ['key'], unique=False)
    op.add_column('features', sa.Column('terminologies', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('features', 'terminologies')
    op.drop_index(op.f('ix_terminologies_key'), table_name='terminologies')
    op.drop_table('terminologies')
    # ### end Alembic commands ###
