"""add unique constraint to terminology key value

Revision ID: c328de375c3d
Revises: dd60fb3ae7a9
Create Date: 2025-08-30 21:33:33.172580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c328de375c3d'
down_revision: Union[str, None] = 'dd60fb3ae7a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_terminology_key_value', 'terminologies', ['key', 'value'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_terminology_key_value', 'terminologies', type_='unique')
    # ### end Alembic commands ###
