"""Alter checks table feature_id col

Revision ID: accbc0c4562a
Revises: 0631bf67b7b8
Create Date: 2025-08-30 09:18:06.199801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'accbc0c4562a'
down_revision: Union[str, None] = '0631bf67b7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('checks_feature_id_key', 'checks', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('checks_feature_id_key', 'checks', ['feature_id'])
    # ### end Alembic commands ###
