"""Create system prompts table

Revision ID: e9bffff46348
Revises: 487dfbd44219
Create Date: 2025-08-30 12:10:01.919637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9bffff46348'
down_revision: Union[str, None] = '487dfbd44219'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_prompt_versions',
    sa.Column('agent_type', sa.Enum('FEATURE_EVAL_AGENT', 'ROU_EXTRACT_AGENT', name='agenttype'), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('patch_summary', sa.Text(), nullable=True),
    sa.Column('parent_version', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('active_prompts',
    sa.Column('agent_type', sa.Enum('FEATURE_EVAL_AGENT', 'ROU_EXTRACT_AGENT', name='agenttype'), nullable=False),
    sa.Column('active_prompt_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['active_prompt_id'], ['system_prompt_versions.id'], ),
    sa.PrimaryKeyConstraint('agent_type')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('active_prompts')
    op.drop_table('system_prompt_versions')
    # ### end Alembic commands ###
    sa.Enum('FEATURE_EVAL_AGENT', 'ROU_EXTRACT_AGENT', name='agenttype').drop(op.get_bind(), checkfirst=False)