"""Cascade regulation deletion

Revision ID: 05b16f5d5751
Revises: f04978185293
Create Date: 2025-08-31 05:24:44.301920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05b16f5d5751'
down_revision: Union[str, None] = 'f04978185293'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('regulatory_obligation_units_source_id_fkey', 'regulatory_obligation_units', type_='foreignkey')
    op.create_foreign_key('regulatory_obligation_units_source_id_fkey', 'regulatory_obligation_units', 'regulations', ['source_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('regulatory_obligation_units_source_id_fkey', 'regulatory_obligation_units', type_='foreignkey')
    op.create_foreign_key('regulatory_obligation_units_source_id_fkey', 'regulatory_obligation_units', 'regulations', ['source_id'], ['id'])
    # ### end Alembic commands ###
